apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-cm
  namespace: staging
data:
  DATABASE_URL: "postgresql://taskflow:taskflow123@postgres:5432/taskflow"
  REDIS_URL: "redis://redis:6379"
  JWT_SECRET: "dev-secret-change-in-production"
  TASK_SERVICE_PORT: "3002"
